### ISSUE TITLE
Prepare for 1.1.0

### ISSUE THREAD

**Issue by jherdman** [jherdman/ember-cli-chartist#48]
## TODO

- [x] Draft release notes
- [x] Double check code against a prod version of an app
- [x] Ensure Ember CLI is up to date (#49)
- [x] Update build on Travis to use Chrome (#50)
- [x] Ensure Chartist is up to date (#51)
- [x] Update version number (#53)
- [x] Publish the release on Github
- [x] Publish the release on NPM
- [x] Investigate if it's possible to give me powers to publish to NPM so @tylergaw doesn't need to be pestered each time :)

**Comment by jherdman** [comment]
@tylergaw it's that time again. Care to `npm publish` this? I'll look into how I can do this myself too.

**Comment by jherdman** [comment]
Hey @tylergaw. I thought I'd ping you on the npm publish of this release.

**Comment by jamesdixon** [comment]
Just a bump to get this published to NPM or give @jherdman access to do so 👍 

Thanks for all of the hard work!

cc: @tylergaw @jherdman

**Comment by tylergaw** [comment]
oof, sorry for the delay ya'll. I just got back to james in email form and we're getting this sorted. Will have latest version published to npm and James access to everything he needs today/tomorrow.
